# Getting Started with Data Pipelines for ETL

## 🇬🇧 English

Data pipelines are a fundamental component of modern data engineering. Organizations rely on ETL (Extract, Transform, Load) processes to collect data from multiple sources, clean and transform it into a usable format, and finally load it into a database for analysis and reporting.

In this notebook, we will build a simple ETL pipeline using **Python**, **Pandas**, and **PostgreSQL**. Throughout the project, we will extract data from CSV files, perform data cleaning and transformation operations, and then load the processed data into a PostgreSQL database for storage and further analysis.

The dataset used in this project is the **Google Play Store Apps** dataset. It consists of two CSV files:

- **apps_data.csv** – Contains information about Google Play Store applications.
- **review_data.csv** – Contains user reviews and sentiment information for the applications.

By the end of this notebook, you will understand the core stages of an ETL pipeline and learn how Python and PostgreSQL can be integrated to automate data processing workflows.

---

## 🇹🇷 Türkçe

Veri boru hatları (Data Pipelines), modern veri mühendisliğinin temel bileşenlerinden biridir. Kurumlar, farklı kaynaklardan verileri toplamak, temizlemek, dönüştürmek ve analiz edilebilir hale getirerek veritabanlarına aktarmak için **ETL (Extract, Transform, Load)** süreçlerini kullanırlar.

Bu notebook boyunca **Python**, **Pandas** ve **PostgreSQL** kullanılarak basit bir ETL veri hattı geliştirilecektir. Öncelikle CSV dosyalarındaki veriler okunacak, ardından çeşitli veri temizleme ve dönüştürme işlemleri gerçekleştirilecek ve son olarak işlenen veriler PostgreSQL veritabanına yüklenerek analiz için hazır hale getirilecektir.

Bu projede kullanılan veri seti **Google Play Store Apps** veri setidir. Veri seti iki farklı CSV dosyasından oluşmaktadır:

- **apps_data.csv** – Google Play Store uygulamalarına ait bilgileri içerir.
- **review_data.csv** – Uygulamalara ait kullanıcı yorumlarını ve duygu (sentiment) analiz sonuçlarını içerir.

Bu notebook'un sonunda, bir ETL veri hattının temel aşamalarını öğrenmiş ve Python ile PostgreSQL kullanarak uçtan uca bir veri işleme sürecinin nasıl geliştirileceğini uygulamalı olarak görmüş olacaksınız.

# Extracting Data

## 🇬🇧 English

**Data extraction** is the first stage of the ETL (Extract, Transform, Load) process. During this phase, data is collected from one or more sources and prepared for further processing. Depending on the project requirements, data can be extracted from a variety of sources, including:

- REST APIs
- SFTP servers
- Relational databases (PostgreSQL, MySQL, SQL Server, etc.)
- NoSQL databases (Document, Columnar, Key-Value)
- Flat files (CSV, JSON, Excel, Parquet, etc.)

In this notebook, we will extract data from **CSV (Comma-Separated Values)** files using the **Pandas** library. The extracted data will later be cleaned, transformed, and loaded into a **PostgreSQL** database.

The datasets used in this project are:

- **apps_data.csv** – Contains information about Google Play Store applications.
- **review_data.csv** – Contains user reviews and sentiment analysis data.

The following tasks will be completed in this section:

1. Import the Pandas library.
2. Read the **apps_data.csv** file into a DataFrame.
3. Display the first few rows of the applications dataset.
4. Read the **review_data.csv** file into another DataFrame.
5. Display the first few rows of the reviews dataset.
6. Perform a basic Exploratory Data Analysis (EDA) by displaying:
   - Column names
   - Dataset dimensions (rows and columns)
   - Data types of each column

This initial exploration helps us better understand the structure and quality of the data before moving on to the transformation stage.

---

## 🇹🇷 Türkçe

**Veri çıkarma (Extract)**, ETL (Extract, Transform, Load) sürecinin ilk aşamasıdır. Bu aşamada veriler bir veya birden fazla kaynaktan alınarak sonraki işlemler için hazır hale getirilir. Projenin gereksinimlerine bağlı olarak veriler farklı kaynaklardan elde edilebilir. Bunlardan bazıları şunlardır:

- REST API servisleri
- SFTP sunucuları
- İlişkisel veritabanları (PostgreSQL, MySQL, SQL Server vb.)
- NoSQL veritabanları (Doküman, Sütun Bazlı, Anahtar-Değer)
- Düz dosyalar (CSV, JSON, Excel, Parquet vb.)

Bu notebook'ta veriler **Pandas** kütüphanesi kullanılarak **CSV (Comma-Separated Values)** dosyalarından okunacaktır. Elde edilen veriler daha sonra temizlenecek, dönüştürülecek ve **PostgreSQL** veritabanına aktarılacaktır.

Projede kullanılan veri dosyaları şunlardır:

- **apps_data.csv** – Google Play Store uygulamalarına ait bilgileri içerir.
- **review_data.csv** – Uygulamalara ait kullanıcı yorumları ve duygu analizi sonuçlarını içerir.

Bu bölümde aşağıdaki işlemler gerçekleştirilecektir:

1. Pandas kütüphanesinin projeye dahil edilmesi.
2. **apps_data.csv** dosyasının bir DataFrame olarak okunması.
3. Uygulama veri setinin ilk birkaç satırının görüntülenmesi.
4. **review_data.csv** dosyasının ikinci bir DataFrame olarak okunması.
5. İnceleme veri setinin ilk birkaç satırının görüntülenmesi.
6. Temel Keşifsel Veri Analizi (EDA) gerçekleştirilerek aşağıdaki bilgiler incelenecektir:
   - Sütun isimleri
   - Veri setinin satır ve sütun sayısı
   - Her sütunun veri tipi

Bu ilk inceleme sayesinde veri setinin yapısı daha iyi anlaşılacak ve veri dönüştürme aşamasına geçmeden önce olası veri kalitesi sorunları tespit edilebilecektir.

In [4]:
import warnings

warnings.filterwarnings("ignore")

In [1]:
# Import the Pandas library for data manipulation and analysis.
# Pandas provides powerful tools for reading, processing, and analyzing tabular datasets.
# Veri işleme ve analiz işlemleri için Pandas kütüphanesi içe aktarılır.
# Pandas, tablo şeklindeki verileri okumak, düzenlemek ve analiz etmek için güçlü araçlar sunar.
import pandas as pd

# Load the applications dataset into a DataFrame.
# Display the first five rows to perform an initial inspection of the data.
# Uygulama veri seti bir DataFrame'e yüklenir.
# İlk beş satır görüntülenerek verinin genel yapısı ön incelemeden geçirilir.
apps = pd.read_csv("apps_data.csv")
print(apps.head())

# Load the reviews dataset into a separate DataFrame.
# Display the first five rows to understand its structure.
# İnceleme (reviews) veri seti ayrı bir DataFrame'e yüklenir.
# İlk beş satır görüntülenerek veri yapısı incelenir.
reviews = pd.read_csv("review_data.csv")
print(reviews.head())

# Perform a basic Exploratory Data Analysis (EDA).
# Display column names, dataset dimensions, and data types.
# Temel Keşifsel Veri Analizi (EDA) gerçekleştirilir.
# Sütun isimleri, veri setinin boyutu ve veri tipleri görüntülenir.
print(apps.columns)
print(apps.shape)
print(apps.dtypes)

# Display the complete DataFrame for further inspection.
# Veri setinin tamamı görüntülenerek genel yapısı incelenir.
apps

                                                 App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1
1                                Coloring book moana  ART_AND_DESIGN     3.9
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone
1     967   14M     500,000+  Free     0       Everyone
2   87510  8.7M   5,000,000+  Free     0       Everyone
3  215644   25M  50,000,000+  Free     0           Teen
4     967  2.8M     100,000+  Free     0       Everyone

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0
1  Art & Design;Pretend Play  January 15, 2018               2.0.0
2               Art & Design    August 1, 2018               1.2.4
3               Art & Design      June 8, 2018  Varies with device
4    Art & Design;Creativity     June 20, 2018                 1.1

    Android Ver
0  4.0.3 and up
1  4.0.3 and up
2  4.0.3 and up
3    4.2 and up
4    4.4 and up
                     App                                  Translated_Review  \
0  10 Best Foods for You  I like eat delicious food. That's I'm cooking ...
1  10 Best Foods for You    This help eating healthy exercise regular basis
2  10 Best Foods for You                                                NaN
3  10 Best Foods for You         Works great especially going grocery store
4  10 Best Foods for You                                       Best idea us

  Sentiment  Sentiment_Polarity  Sentiment_Subjectivity
0  Positive                1.00                0.533333
1  Positive                0.25                0.288462
2       NaN                 NaN                     NaN
3  Positive                0.40                0.875000
4  Positive                1.00                0.300000
Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')
(10841, 13)
App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

# Building a Reusable Data Extraction Function

## 🇬🇧 English

The previous approach successfully loads the datasets, but it contains repetitive code. One of the most important software development principles is **DRY (Don't Repeat Yourself)**, which encourages developers to avoid writing the same logic multiple times.

Instead of repeating the same code for every dataset, we can create a reusable function that performs the extraction process. This approach improves code readability, maintainability, and scalability, especially when working with multiple data sources.

In this section, we will create a function named **`extract()`** that automates the data extraction process.

The function will perform the following tasks:

1. Accept the file path as an input parameter (`file_path`).
2. Read the CSV file into a Pandas DataFrame.
3. Display useful information about the dataset, including:
   - Number of rows and columns
   - Data types of each column
4. Print instructions explaining how to use the returned DataFrame.
5. Return the extracted DataFrame for use in subsequent ETL stages.

After defining the function, it will be executed twice:

- Once for **apps_data.csv**
- Once for **review_data.csv**

Finally, one of the extracted DataFrames will be displayed to verify that the extraction process completed successfully.

---

## 🇹🇷 Türkçe

Önceki yöntemde veri setleri başarıyla okunmaktadır; ancak aynı kod blokları birden fazla kez tekrar edilmektedir. Yazılım geliştirmede en önemli prensiplerden biri olan **DRY (Don't Repeat Yourself - Kendini Tekrar Etme)** ilkesi, aynı kodun tekrar tekrar yazılmasını önermektedir.

Bu nedenle her veri seti için aynı işlemleri yeniden yazmak yerine, veri okuma işlemini gerçekleştiren yeniden kullanılabilir bir fonksiyon oluşturacağız. Bu yaklaşım kodun okunabilirliğini artırır, bakımını kolaylaştırır ve farklı veri kaynaklarıyla çalışırken ölçeklenebilir bir yapı sağlar.

Bu bölümde **`extract()`** isimli bir fonksiyon geliştirilecektir.

Fonksiyon aşağıdaki işlemleri gerçekleştirecektir:

1. Dosya yolunu (`file_path`) parametre olarak alacaktır.
2. CSV dosyasını bir Pandas DataFrame'ine okuyacaktır.
3. Veri setine ait temel bilgileri ekrana yazdıracaktır:
   - Satır ve sütun sayısı
   - Her sütunun veri tipi
4. Fonksiyonun döndürdüğü DataFrame'in nasıl kullanılacağına dair bilgilendirici mesajlar gösterecektir.
5. Okunan DataFrame'i ETL sürecinin sonraki aşamalarında kullanılmak üzere döndürecektir.

Fonksiyon tanımlandıktan sonra iki farklı veri seti için çalıştırılacaktır:

- **apps_data.csv**
- **review_data.csv**

Son olarak, okunan DataFrame'lerden biri görüntülenerek veri çıkarma işleminin başarıyla tamamlandığı doğrulanacaktır.

In [2]:
# Define a reusable function to load a CSV file and display basic information.
# This function improves code reusability by eliminating repetitive code.
# Bir CSV dosyasını okuyup temel bilgilerini görüntüleyen yeniden kullanılabilir bir fonksiyon tanımlanır.
# Bu yaklaşım, aynı işlemleri tekrar yazmayı önleyerek kodun daha düzenli ve sürdürülebilir olmasını sağlar.

def extract(file_path):
    """
    Description:
        This function reads a CSV file and displays basic information
        about the extracted dataset.

    Açıklama:
        Bu fonksiyon belirtilen yoldaki CSV dosyasını okur ve
        veri setine ait temel bilgileri ekrana yazdırır.

    Args:
        file_path (str): Path to the CSV file.

    Parametreler:
        file_path (str): Okunacak CSV dosyasının yolu.

    Returns:
        pd.DataFrame: The loaded dataset.

    Döndürür:
        pd.DataFrame: Okunan veri setini DataFrame olarak döndürür.
    """

    # Read the CSV file into a Pandas DataFrame.
    # CSV dosyası Pandas DataFrame'ine aktarılır.
    data = pd.read_csv(file_path)

    # Display general information about the dataset.
    # Veri seti hakkında genel bilgiler görüntülenir.

    print(f"Here is a little bit of information about the data stored in '{file_path}':")
    print(f"'{file_path}' dosyasında bulunan veri setine ait temel bilgiler aşağıda gösterilmektedir.\n")

    print(f"There are {data.shape[0]} rows and {data.shape[1]} columns in this DataFrame.")
    print(f"Bu DataFrame toplam {data.shape[0]} satır ve {data.shape[1]} sütundan oluşmaktadır.\n")

    print("The columns in this DataFrame have the following data types:")
    print("Bu DataFrame'deki sütunların veri tipleri aşağıdaki gibidir:")
    print(data.dtypes)

    print(f"\nTo view the DataFrame extracted from '{file_path}', display the value returned by this function!")
    print(f"'{file_path}' dosyasından okunan veri setini görüntülemek için fonksiyonun döndürdüğü değeri görüntüleyebilirsiniz.\n")

    # Return the DataFrame for further analysis.
    # DataFrame daha sonraki analizlerde kullanılmak üzere döndürülür.
    return data


# Load the applications dataset using the reusable function.
# Yeniden kullanılabilir fonksiyon kullanılarak uygulama veri seti yüklenir.
apps_data = extract("apps_data.csv")

# Load the reviews dataset using the same function.
# Aynı fonksiyon kullanılarak inceleme veri seti yüklenir.
reviews_data = extract("review_data.csv")

# Display one of the extracted DataFrames for inspection.
# Okunan veri setlerinden biri görüntülenerek yapısı incelenir.
reviews_data

Here is a little bit of information about the data stored in 'apps_data.csv':
'apps_data.csv' dosyasında bulunan veri setine ait temel bilgiler aşağıda gösterilmektedir.

There are 10841 rows and 13 columns in this DataFrame.
Bu DataFrame toplam 10841 satır ve 13 sütundan oluşmaktadır.

The columns in this DataFrame have the following data types:
Bu DataFrame'deki sütunların veri tipleri aşağıdaki gibidir:
App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

To view the DataFrame extracted from 'apps_data.csv', display the value returned by this function!
'apps_data.csv' dosyasından okunan veri setini görüntülemek için fonksiyonun döndürdüğü değeri görüntüleyebilirsiniz.

Here is a little bit of information about the data stored in 'review_data.csv':
'review_data.csv' dosyasında bulunan veri setine ait temel bilgiler aşağıda gösterilmektedir.

There are 64295 rows and 5 columns in this DataFrame.
Bu DataFrame toplam 64295 satır ve 5 sütundan oluşmaktadır.

The columns in this DataFrame have the following data types:
Bu DataFrame'deki sütunların veri tipleri aşağıdaki gibidir:
App                        object
Translated_Review          object
Sentiment                  object
Sentiment_Polarity        float64
Sentiment_Subjectivity    float64
dtype: object

To view the DataFrame extracted from 'review_data.csv', display the value returned by this function!
'review_data.csv' dosyasından okunan veri setini görüntülemek için fonksiyonun döndürdüğü değeri görüntüleyebilirsiniz.

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000
...,...,...,...,...,...
64290,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64291,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64292,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64293,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64294,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN

# Transforming Data

## 🇬🇧 English

The **Transform** stage is the second phase of the ETL (Extract, Transform, Load) process. During this stage, the extracted data is cleaned, filtered, combined, and prepared for analysis. Data transformation improves data quality and ensures that only relevant information is retained for downstream processes.

In this notebook, we are interested in analyzing applications that belong to the **"FOOD_AND_DRINK"** category. To accomplish this, we will create a reusable **`transform()`** function that performs several data transformation operations.

The function will complete the following tasks:

1. Accept the following parameters:
   - `apps`
   - `reviews`
   - `category`
   - `min_rating`
   - `min_reviews`

2. Remove duplicate records from both the applications and reviews datasets.

3. Filter only the applications that belong to the selected category.

4. Retrieve the corresponding reviews for those applications and calculate the **average sentiment polarity** for each application.

5. Merge the aggregated review information back into the applications dataset.

6. Keep only the columns required for the analysis:

   - `App`
   - `Rating`
   - `Reviews`
   - `Installs`
   - `Sentiment_Polarity`

7. Convert the **Reviews** column into an integer data type.

8. Filter applications that satisfy both conditions:
   - Rating greater than the specified minimum rating.
   - Number of reviews greater than the specified minimum review count.

9. Sort the final dataset by:
   - Rating (descending)
   - Number of reviews (descending)

10. Save the transformed dataset as **top_apps.csv** for later use in the loading stage.

Finally, the function will be executed for the **"FOOD_AND_DRINK"** category using:
- Minimum rating: **4.0**
- Minimum number of reviews: **1000**

The resulting dataset will contain only the highest-rated and most frequently reviewed applications that satisfy the specified criteria.

---

## 🇹🇷 Türkçe

**Transform (Dönüştürme)** aşaması, ETL (Extract, Transform, Load) sürecinin ikinci adımıdır. Bu aşamada veri temizlenir, filtrelenir, birleştirilir ve analiz için uygun hale getirilir. Veri dönüştürme işlemleri, veri kalitesini artırırken yalnızca analiz için gerekli bilgilerin korunmasını sağlar.

Bu notebook'ta **"FOOD_AND_DRINK"** kategorisindeki uygulamalar analiz edilecektir. Bunun için çeşitli veri dönüştürme işlemlerini gerçekleştiren yeniden kullanılabilir **`transform()`** fonksiyonu oluşturulacaktır.

Fonksiyon aşağıdaki işlemleri gerçekleştirecektir:

1. Aşağıdaki parametreleri alacaktır:
   - `apps`
   - `reviews`
   - `category`
   - `min_rating`
   - `min_reviews`

2. Hem uygulama hem de inceleme veri setlerindeki yinelenen kayıtları kaldıracaktır.

3. Yalnızca seçilen kategoriye ait uygulamaları filtreleyecektir.

4. Bu uygulamalara ait kullanıcı yorumlarını alacak ve her uygulama için **ortalama duygu (Sentiment Polarity)** skorunu hesaplayacaktır.

5. Hesaplanan duygu skorlarını uygulama veri seti ile birleştirecektir.

6. Analizde kullanılacak aşağıdaki sütunları koruyacaktır:

   - `App`
   - `Rating`
   - `Reviews`
   - `Installs`
   - `Sentiment_Polarity`

7. **Reviews** sütununu tam sayı veri tipine dönüştürecektir.

8. Aşağıdaki kriterleri sağlayan uygulamaları filtreleyecektir:
   - Belirlenen minimum puandan daha yüksek puana sahip olmak.
   - Belirlenen minimum inceleme sayısından daha fazla incelemeye sahip olmak.

9. Sonuç veri setini aşağıdaki ölçütlere göre azalan sırada sıralayacaktır:
   - Uygulama puanı (Rating)
   - İnceleme sayısı (Reviews)

10. Dönüştürülen veri setini, ETL sürecinin **Load** aşamasında kullanılmak üzere **top_apps.csv** dosyası olarak kaydedecektir.

Son olarak fonksiyon aşağıdaki parametrelerle çalıştırılacaktır:

- Kategori: **"FOOD_AND_DRINK"**
- Minimum puan: **4.0**
- Minimum inceleme sayısı: **1000**

Elde edilen veri seti, belirtilen kriterleri karşılayan en yüksek puanlı ve en fazla kullanıcı incelemesine sahip uygulamalardan oluşacaktır. Bu veri seti bir sonraki aşamada **PostgreSQL** veritabanına aktarılacaktır.

In [5]:
# Define a reusable function to clean, transform, and filter the applications dataset.
# The function combines application and review data, applies several transformations,
# and returns the most popular applications based on the specified criteria.
#
# Uygulama ve inceleme veri setlerini temizleyen, dönüştüren ve filtreleyen
# yeniden kullanılabilir bir fonksiyon tanımlanır. Fonksiyon, iki veri setini
# birleştirerek belirlenen kriterlere göre en popüler uygulamaları döndürür.

def transform(apps, reviews, category, min_rating, min_reviews):
    """
    Description:
        Transform the apps and reviews data to include only applications in the
        specified category, calculate the average sentiment polarity, keep the
        required columns, filter less popular applications, and return the
        transformed DataFrame sorted by rating and number of reviews.

    Açıklama:
        Uygulama ve inceleme verilerini dönüştürerek yalnızca belirtilen
        kategoriye ait uygulamaları seçer, ortalama duygu (sentiment)
        skorunu hesaplar, gerekli sütunları korur, popüler olmayan
        uygulamaları filtreler ve sonucu puan ile inceleme sayısına göre
        sıralanmış şekilde döndürür.

    Args:
        apps (pd.DataFrame): Applications dataset.
        reviews (pd.DataFrame): Reviews dataset.
        category (str): Target application category.
        min_rating (float): Minimum application rating.
        min_reviews (int): Minimum number of reviews.

    Parametreler:
        apps (pd.DataFrame): Uygulama veri seti.
        reviews (pd.DataFrame): İnceleme veri seti.
        category (str): Filtrelenecek uygulama kategorisi.
        min_rating (float): Minimum uygulama puanı.
        min_reviews (int): Minimum inceleme sayısı.

    Returns:
        pd.DataFrame: Transformed and filtered dataset.

    Döndürür:
        pd.DataFrame: Dönüştürülmüş ve filtrelenmiş veri seti.
    """

    # Display information about the transformation process.
    # Gerçekleştirilecek veri dönüştürme işlemi hakkında bilgi verilir.
    print(
        f"Transforming data to curate a dataset with all {category} apps and their "
        f"corresponding reviews with a rating of at least {min_rating} and "
        f"{min_reviews} reviews."
    )

    print(
        f"Veri dönüştürme işlemi başlatıldı. '{category}' kategorisindeki, "
        f"puanı en az {min_rating} olan ve en az {min_reviews} incelemeye sahip "
        f"uygulamalar analiz edilmektedir.\n"
    )

    # Remove duplicate application records based on the App column.
    # App sütununa göre yinelenen uygulama kayıtları kaldırılır.
    apps = apps.drop_duplicates(["App"])

    # Remove duplicate review records.
    # Yinelenen inceleme kayıtları kaldırılır.
    reviews = reviews.drop_duplicates()

    # Filter applications that belong to the selected category.
    # Belirlenen kategoriye ait uygulamalar filtrelenir.
    subset_apps = apps.loc[apps["Category"] == category, :]

    # Keep only reviews that belong to the filtered applications.
    # Yalnızca filtrelenen uygulamalara ait incelemeler seçilir.
    subset_reviews = reviews.loc[
        reviews["App"].isin(subset_apps["App"]),
        ["App", "Sentiment_Polarity"]
    ]

    # Calculate the average sentiment polarity for each application.
    # Her uygulama için ortalama duygu (sentiment) skoru hesaplanır.
    aggregated_reviews = subset_reviews.groupby(by="App").mean()

    # Merge application information with the aggregated review scores.
    # Uygulama bilgileri ile ortalama duygu skorları birleştirilir.
    joined_apps_reviews = subset_apps.join(
        aggregated_reviews,
        on="App",
        how="left"
    )

    # Keep only the columns required for the analysis.
    # Analiz için gerekli sütunlar seçilir.
    filtered_apps_reviews = joined_apps_reviews.loc[
        :,
        ["App", "Rating", "Reviews", "Installs", "Sentiment_Polarity"]
    ]

    # Convert the Reviews column to integer format.
    # Reviews sütunu tam sayı veri tipine dönüştürülür.
    filtered_apps_reviews = filtered_apps_reviews.astype({"Reviews": "int32"})

    # Filter applications that satisfy the minimum rating and review thresholds.
    # Minimum puan ve minimum inceleme sayısı kriterlerini sağlayan uygulamalar seçilir.
    top_apps = filtered_apps_reviews.loc[
        (filtered_apps_reviews["Rating"] > min_rating)
        & (filtered_apps_reviews["Reviews"] > min_reviews),
        :
    ]

    # Sort the applications by rating and review count in descending order.
    # Uygulamalar puan ve inceleme sayısına göre azalan şekilde sıralanır.
    top_apps.sort_values(
        by=["Rating", "Reviews"],
        ascending=False,
        inplace=True
    )

    # Reset the index after sorting.
    # Sıralama sonrasında indeks yeniden oluşturulur.
    top_apps.reset_index(drop=True, inplace=True)

    # Save the transformed dataset as a CSV file.
    # Dönüştürülen veri seti CSV dosyası olarak kaydedilir.
    top_apps.to_csv("top_apps.csv", index=False)

    # Display information about the generated dataset.
    # Oluşturulan veri seti hakkında bilgi verilir.
    print(
        f"The transformed DataFrame contains {top_apps.shape[0]} rows "
        f"and {top_apps.shape[1]} columns. "
        f"It has been saved as 'top_apps.csv' and is ready for further analysis."
    )

    print(
        f"Dönüştürülen DataFrame {top_apps.shape[0]} satır ve "
        f"{top_apps.shape[1]} sütundan oluşmaktadır. "
        f"Veri seti 'top_apps.csv' dosyası olarak kaydedildi ve "
        f"analiz için hazır hale getirildi."
    )

    # Return the transformed DataFrame.
    # Dönüştürülen DataFrame döndürülür.
    return top_apps


# Execute the transformation function using the specified parameters.
# Belirlenen parametrelerle veri dönüştürme fonksiyonu çalıştırılır.
top_apps_data = transform(
    apps=apps_data,
    reviews=reviews_data,
    category="FOOD_AND_DRINK",
    min_rating=4.0,
    min_reviews=1000
)

# Display the transformed dataset.
# Dönüştürülen veri seti görüntülenir.
top_apps_data

Transforming data to curate a dataset with all FOOD_AND_DRINK apps and their corresponding reviews with a rating of at least 4.0 and 1000 reviews.
Veri dönüştürme işlemi başlatıldı. 'FOOD_AND_DRINK' kategorisindeki, puanı en az 4.0 olan ve en az 1000 incelemeye sahip uygulamalar analiz edilmektedir.

The transformed DataFrame contains 54 rows and 5 columns. It has been saved as 'top_apps.csv' and is ready for further analysis.
Dönüştürülen DataFrame 54 satır ve 5 sütundan oluşmaktadır. Veri seti 'top_apps.csv' dosyası olarak kaydedildi ve analiz için hazır hale getirildi.

,App,Rating,Reviews,Installs,Sentiment_Polarity
0,SarashpazPapion (Cooking with Chef Bowls),4.8,1250,"50,000+",NaN
1,Domino's Pizza USA,4.7,1032935,"10,000,000+",0.226971
2,Tastely,4.7,611136,"10,000,000+",NaN
3,Delicious Recipes,4.7,129737,"1,000,000+",NaN
4,BeyondMenu Food Delivery,4.7,51517,"1,000,000+",0.408743
5,Recipes Pastries and homemade pies More than 5...,4.7,14065,"500,000+",NaN
6,Pastry & Cooking (Without Net),4.7,6118,"1,000,000+",NaN
7,Simple Recipes,4.7,3803,"500,000+",NaN
8,Easy Recipes,4.7,2707,"100,000+",0.284777
9,OpenTable: Restaurants Near Me,4.6,90242,"5,000,000+",NaN
10,DELISH KITCHEN - FREE recipe movies make food ...,4.6,32997,"1,000,000+",NaN
11,Kitchen Stories - Recipes & Cooking,4.6,22015,"1,000,000+",NaN
12,My Recipes Cookbook : RecetteTek,4.6,11707,"100,000+",NaN
13,EatStreet Food Delivery App,4.6,7690,"100,000+",0.383265
14,"Eat Fast Prepare ""Without Internet""",4.6,4925,"1,000,000+",NaN
15,My CookBook Pro (Ad Free),4.6,2129,"10,000+",NaN
16,Easy and quick desserts,4.6,1398,"100,000+",NaN
17,Starbucks,4.5,455377,"10,000,000+",NaN
18,Grubhub: Food Delivery,4.5,155944,"5,000,000+",0.122739
19,Cookpad,4.5,131569,"10,000,000+",0.257437
20,Talabat: Food Delivery,4.5,116403,"5,000,000+",NaN
21,DoorDash - Food Delivery,4.5,104504,"1,000,000+",0.072407
22,Yummly Recipes & Shopping List,4.5,91359,"1,000,000+",NaN
23,Allrecipes Dinner Spinner,4.5,61881,"5,000,000+",0.273000
24,Seamless Food Delivery/Takeout,4.5,35218,"1,000,000+",NaN
25,My CookBook (Recipe Manager),4.5,22071,"1,000,000+",NaN
26,ChefTap Recipes & Grocery List,4.5,9066,"500,000+",NaN
27,Whataburger,4.5,5093,"500,000+",NaN
28,BURGER KING® Puerto Rico,4.5,2448,"100,000+",NaN
29,Pizza Hut,4.4,321134,"10,000,000+",NaN
30,Delivery yogi.,4.4,90042,"10,000,000+",NaN
31,Instacart: Grocery Delivery,4.4,17071,"1,000,000+",NaN
32,Recipe Keeper,4.4,1962,"100,000+",NaN
33,Zomato - Restaurant Finder and Food Delivery App,4.3,511228,"10,000,000+",NaN
34,"Delivery Club-food delivery: pizza, sushi, bur...",4.3,151080,"5,000,000+",NaN
35,Delivery trough - delivery trough delivery trough,4.3,58316,"5,000,000+",NaN
36,Eat24 Food Delivery & Takeout,4.3,40116,"1,000,000+",0.171611
37,TheFork - Restaurants booking and special offers,4.3,37517,"5,000,000+",NaN
38,"BigOven Recipes, Meal Planner, Grocery List & ...",4.3,31986,"1,000,000+",0.328222
39,GialloZafferano: Recipes,4.3,30224,"1,000,000+",NaN
40,Chick-fil-A,4.3,28008,"5,000,000+",NaN
41,SONIC Drive-In,4.3,19314,"1,000,000+",NaN
42,Uber Eats: Local Food Delivery,4.2,333208,"10,000,000+",NaN
43,Dunkin' Donuts,4.2,68103,"1,000,000+",0.196560
44,Panera Bread,4.2,10159,"1,000,000+",NaN
45,Dr. Oetker recipe ideas,4.2,8509,"1,000,000+",NaN
46,Caviar - Food Delivery,4.2,3755,"100,000+",0.217375
47,Foursquare City Guide,4.1,483960,"10,000,000+",0.200279
48,Cookpad - FREE recipe search makes fun cooking...,4.1,64784,"10,000,000+",NaN
49,Cookbook Recipes,4.1,46539,"5,000,000+",0.565437
50,Chef - Recipes & Cooking,4.1,32405,"5,000,000+",NaN
51,Frigo Magic: Easy recipe idea and anti-waste,4.1,2473,"500,000+",NaN
52,"delivery.com: Order Food, Alcohol & Laundry",4.1,1920,"100,000+",NaN
53,Paprika Recipe Manager,4.1,1268,"50,000+",NaN

# Loading Data

## 🇬🇧 English

The **Load** stage is the final step of the ETL (Extract, Transform, Load) process. After the data has been extracted and transformed, it is loaded into a database where it can be stored, queried, and analyzed efficiently.

In this notebook, instead of using SQLite, we will load the transformed dataset into a **PostgreSQL** database. PostgreSQL is one of the most popular open-source relational database management systems and is widely used in production-grade data engineering projects.

To accomplish this, we will use **Pandas**, **SQLAlchemy**, and the **psycopg2** PostgreSQL driver.

The **`load()`** function will perform the following tasks:

1. Accept the following parameters:
   - `dataframe`
   - `host`
   - `port`
   - `database_name`
   - `user`
   - `password`
   - `table_name`

2. Create a connection to the PostgreSQL database using SQLAlchemy.

3. Load the DataFrame into the specified PostgreSQL table.
   - Replace the table if it already exists.
   - Do not write the DataFrame index.

4. Read the table back from PostgreSQL using `pd.read_sql()`.

5. Validate the loading process by comparing the dimensions of the original and loaded DataFrames.

6. Display informative messages indicating whether the loading process completed successfully.

7. Return the DataFrame retrieved from PostgreSQL.

Finally, the function will be executed using the transformed **`top_apps_data`** DataFrame and will store the data in the **`top_apps`** table of the target PostgreSQL database.

This validation step helps ensure that the ETL pipeline has successfully transferred the transformed data into the database without data loss.

---

## 🇹🇷 Türkçe

**Load (Yükleme)** aşaması, ETL (Extract, Transform, Load) sürecinin son adımıdır. Veriler çıkarılıp dönüştürüldükten sonra, uzun süreli saklama, sorgulama ve analiz işlemleri için bir veritabanına aktarılır.

Bu notebook'ta SQLite yerine dönüştürülen veri seti **PostgreSQL** veritabanına yüklenecektir. PostgreSQL, açık kaynaklı, güçlü ve üretim ortamlarında yaygın olarak kullanılan ilişkisel bir veritabanı yönetim sistemidir.

Bu işlem için **Pandas**, **SQLAlchemy** ve **psycopg2** PostgreSQL sürücüsü kullanılacaktır.

Oluşturulacak **`load()`** fonksiyonu aşağıdaki işlemleri gerçekleştirecektir:

1. Aşağıdaki parametreleri alacaktır:
   - `dataframe`
   - `host`
   - `port`
   - `database_name`
   - `user`
   - `password`
   - `table_name`

2. SQLAlchemy kullanılarak PostgreSQL veritabanına bağlantı oluşturacaktır.

3. DataFrame'i belirtilen PostgreSQL tablosuna yazacaktır.
   - Tablo mevcutsa yeniden oluşturulacaktır (`replace`).
   - DataFrame indeks sütunu veritabanına yazılmayacaktır.

4. Yazılan tablo doğrulama amacıyla `pd.read_sql()` fonksiyonu kullanılarak PostgreSQL'den tekrar okunacaktır.

5. Orijinal DataFrame ile veritabanından okunan DataFrame'in satır ve sütun sayıları karşılaştırılarak veri yükleme işlemi doğrulanacaktır.

6. Veri yükleme işleminin başarılı veya başarısız olduğunu belirten bilgilendirici mesajlar ekrana yazdırılacaktır.

7. PostgreSQL veritabanından okunan doğrulanmış DataFrame döndürülecektir.

Son olarak fonksiyon, dönüştürülen **`top_apps_data`** veri seti kullanılarak çalıştırılacak ve veriler hedef PostgreSQL veritabanındaki **`top_apps`** tablosuna aktarılacaktır.

Bu doğrulama adımı sayesinde ETL veri hattının dönüştürülen verileri PostgreSQL veritabanına eksiksiz ve doğru şekilde aktardığı kontrol edilmiş olacaktır.

In [7]:
# Import the required library for connecting to PostgreSQL.
# PostgreSQL veritabanına bağlanmak için gerekli kütüphane içe aktarılır.
from sqlalchemy import create_engine

# Define a reusable function to load a DataFrame into a PostgreSQL database
# and validate that the data has been loaded correctly.
#
# Bir DataFrame'i PostgreSQL veritabanına yükleyen ve
# yüklenen veriyi doğrulayan yeniden kullanılabilir bir fonksiyon tanımlanır.

def load(dataframe, host, port, database_name, user, password, table_name):
    """
    Description:
        Loads a DataFrame into a PostgreSQL database and validates
        that the loaded table matches the original DataFrame.

    Açıklama:
        Bir DataFrame'i PostgreSQL veritabanına yükler ve
        yüklenen tablonun orijinal veriyle aynı yapıya sahip olduğunu doğrular.

    Args:
        dataframe (pd.DataFrame): Data to be loaded.
        host (str): PostgreSQL server address.
        port (int): PostgreSQL server port.
        database_name (str): Database name.
        user (str): PostgreSQL username.
        password (str): PostgreSQL password.
        table_name (str): Target table name.

    Parametreler:
        dataframe (pd.DataFrame): Yüklenecek veri.
        host (str): PostgreSQL sunucu adresi.
        port (int): PostgreSQL port numarası.
        database_name (str): Veritabanı adı.
        user (str): PostgreSQL kullanıcı adı.
        password (str): PostgreSQL şifresi.
        table_name (str): Verinin yazılacağı tablo adı.

    Returns:
        pd.DataFrame

    Döndürür:
        pd.DataFrame: Veritabanından okunarak doğrulanan veri.
    """

    # Create the PostgreSQL connection engine.
    # PostgreSQL bağlantısı oluşturulur.
    engine = create_engine(
        f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database_name}"
    )

    # Load the DataFrame into PostgreSQL.
    # DataFrame PostgreSQL tablosuna yazılır.
    dataframe.to_sql(
        name=table_name,
        con=engine,
        if_exists="replace",
        index=False
    )

    print("The original DataFrame has been successfully loaded into PostgreSQL.")
    print("Orijinal DataFrame başarıyla PostgreSQL veritabanına yüklendi.\n")

    # Read the table back from PostgreSQL.
    # Doğrulama amacıyla tablo tekrar okunur.
    loaded_dataframe = pd.read_sql(
        sql=f"SELECT * FROM {table_name}",
        con=engine
    )

    print("The loaded table has been read from PostgreSQL for validation.")
    print("Yüklenen tablo doğrulama amacıyla PostgreSQL veritabanından okunmuştur.\n")

    # Validate that both DataFrames have the same dimensions.
    # İki DataFrame'in aynı boyutta olup olmadığı doğrulanır.
    try:
        assert dataframe.shape == loaded_dataframe.shape

        print(
            f"Success! The '{table_name}' table has been successfully loaded and validated."
        )
        print(
            f"Başarılı! '{table_name}' tablosu PostgreSQL veritabanına başarıyla yüklendi ve doğrulandı."
        )

    except AssertionError:

        print(
            "Validation failed! The DataFrame shape differs before and after loading."
        )
        print(
            "Doğrulama başarısız! Veri yükleme öncesi ve sonrası DataFrame boyutları farklıdır."
        )

    return loaded_dataframe


# Load the transformed dataset into PostgreSQL.
# Dönüştürülen veri PostgreSQL veritabanına yüklenir.
top_apps_loaded = load(
    dataframe=top_apps_data,
    host="localhost",
    port=5432,
    database_name="market_research",
    user="postgres",
    password="12345",
    table_name="top_apps"
)

# Display the loaded data.
# Veritabanından okunan doğrulanmış veri görüntülenir.
top_apps_loaded

The original DataFrame has been successfully loaded into PostgreSQL.
Orijinal DataFrame başarıyla PostgreSQL veritabanına yüklendi.

The loaded table has been read from PostgreSQL for validation.
Yüklenen tablo doğrulama amacıyla PostgreSQL veritabanından okunmuştur.

Success! The 'top_apps' table has been successfully loaded and validated.
Başarılı! 'top_apps' tablosu PostgreSQL veritabanına başarıyla yüklendi ve doğrulandı.

,App,Rating,Reviews,Installs,Sentiment_Polarity
0,SarashpazPapion (Cooking with Chef Bowls),4.8,1250,"50,000+",NaN
1,Domino's Pizza USA,4.7,1032935,"10,000,000+",0.226971
2,Tastely,4.7,611136,"10,000,000+",NaN
3,Delicious Recipes,4.7,129737,"1,000,000+",NaN
4,BeyondMenu Food Delivery,4.7,51517,"1,000,000+",0.408743
5,Recipes Pastries and homemade pies More than 5...,4.7,14065,"500,000+",NaN
6,Pastry & Cooking (Without Net),4.7,6118,"1,000,000+",NaN
7,Simple Recipes,4.7,3803,"500,000+",NaN
8,Easy Recipes,4.7,2707,"100,000+",0.284777
9,OpenTable: Restaurants Near Me,4.6,90242,"5,000,000+",NaN
10,DELISH KITCHEN - FREE recipe movies make food ...,4.6,32997,"1,000,000+",NaN
11,Kitchen Stories - Recipes & Cooking,4.6,22015,"1,000,000+",NaN
12,My Recipes Cookbook : RecetteTek,4.6,11707,"100,000+",NaN
13,EatStreet Food Delivery App,4.6,7690,"100,000+",0.383265
14,"Eat Fast Prepare ""Without Internet""",4.6,4925,"1,000,000+",NaN
15,My CookBook Pro (Ad Free),4.6,2129,"10,000+",NaN
16,Easy and quick desserts,4.6,1398,"100,000+",NaN
17,Starbucks,4.5,455377,"10,000,000+",NaN
18,Grubhub: Food Delivery,4.5,155944,"5,000,000+",0.122739
19,Cookpad,4.5,131569,"10,000,000+",0.257437
20,Talabat: Food Delivery,4.5,116403,"5,000,000+",NaN
21,DoorDash - Food Delivery,4.5,104504,"1,000,000+",0.072407
22,Yummly Recipes & Shopping List,4.5,91359,"1,000,000+",NaN
23,Allrecipes Dinner Spinner,4.5,61881,"5,000,000+",0.273000
24,Seamless Food Delivery/Takeout,4.5,35218,"1,000,000+",NaN
25,My CookBook (Recipe Manager),4.5,22071,"1,000,000+",NaN
26,ChefTap Recipes & Grocery List,4.5,9066,"500,000+",NaN
27,Whataburger,4.5,5093,"500,000+",NaN
28,BURGER KING® Puerto Rico,4.5,2448,"100,000+",NaN
29,Pizza Hut,4.4,321134,"10,000,000+",NaN
30,Delivery yogi.,4.4,90042,"10,000,000+",NaN
31,Instacart: Grocery Delivery,4.4,17071,"1,000,000+",NaN
32,Recipe Keeper,4.4,1962,"100,000+",NaN
33,Zomato - Restaurant Finder and Food Delivery App,4.3,511228,"10,000,000+",NaN
34,"Delivery Club-food delivery: pizza, sushi, bur...",4.3,151080,"5,000,000+",NaN
35,Delivery trough - delivery trough delivery trough,4.3,58316,"5,000,000+",NaN
36,Eat24 Food Delivery & Takeout,4.3,40116,"1,000,000+",0.171611
37,TheFork - Restaurants booking and special offers,4.3,37517,"5,000,000+",NaN
38,"BigOven Recipes, Meal Planner, Grocery List & ...",4.3,31986,"1,000,000+",0.328222
39,GialloZafferano: Recipes,4.3,30224,"1,000,000+",NaN
40,Chick-fil-A,4.3,28008,"5,000,000+",NaN
41,SONIC Drive-In,4.3,19314,"1,000,000+",NaN
42,Uber Eats: Local Food Delivery,4.2,333208,"10,000,000+",NaN
43,Dunkin' Donuts,4.2,68103,"1,000,000+",0.196560
44,Panera Bread,4.2,10159,"1,000,000+",NaN
45,Dr. Oetker recipe ideas,4.2,8509,"1,000,000+",NaN
46,Caviar - Food Delivery,4.2,3755,"100,000+",0.217375
47,Foursquare City Guide,4.1,483960,"10,000,000+",0.200279
48,Cookpad - FREE recipe search makes fun cooking...,4.1,64784,"10,000,000+",NaN
49,Cookbook Recipes,4.1,46539,"5,000,000+",0.565437
50,Chef - Recipes & Cooking,4.1,32405,"5,000,000+",NaN
51,Frigo Magic: Easy recipe idea and anti-waste,4.1,2473,"500,000+",NaN
52,"delivery.com: Order Food, Alcohol & Laundry",4.1,1920,"100,000+",NaN
53,Paprika Recipe Manager,4.1,1268,"50,000+",NaN

# Running the ETL Pipeline

## 🇬🇧 English

With all the ETL functions implemented and tested individually, the final step is to execute the complete pipeline from start to finish. This demonstrates how the **Extract**, **Transform**, and **Load** stages work together as a single automated workflow.

During this stage, the pipeline will perform the following operations sequentially:

1. Import the required Python libraries, including **Pandas**, **SQLAlchemy**, and the PostgreSQL driver (**psycopg2**).

2. Extract the source datasets by calling the **`extract()`** function for:
   - `apps_data.csv`
   - `review_data.csv`

3. Transform the extracted data by executing the **`transform()`** function with the following parameters:
   - `category="FOOD_AND_DRINK"`
   - `min_rating=4.0`
   - `min_reviews=1000`

4. Load the transformed DataFrame into the **`top_apps`** table of the target **PostgreSQL** database by calling the **`load()`** function.

5. Validate the loading process by reading the table back from PostgreSQL and comparing it with the original DataFrame.

6. Display the final output to verify that the entire ETL pipeline completed successfully.

Executing the complete pipeline demonstrates how raw CSV data can be automatically processed, transformed into meaningful information, and stored in a relational database for future analysis.

---

## 🇹🇷 Türkçe

ETL sürecini oluşturan tüm fonksiyonlar geliştirildikten ve ayrı ayrı test edildikten sonra son adım, veri hattını baştan sona çalıştırmaktır. Bu aşama, **Extract (Veri Çıkarma)**, **Transform (Veri Dönüştürme)** ve **Load (Veri Yükleme)** adımlarının tek bir otomatik iş akışı içerisinde nasıl birlikte çalıştığını göstermektedir.

Bu bölümde veri hattı aşağıdaki işlemleri sırasıyla gerçekleştirecektir:

1. Gerekli Python kütüphaneleri (**Pandas**, **SQLAlchemy** ve PostgreSQL sürücüsü **psycopg2**) projeye dahil edilecektir.

2. **`extract()`** fonksiyonu kullanılarak aşağıdaki veri dosyaları okunacaktır:
   - `apps_data.csv`
   - `review_data.csv`

3. Okunan veriler **`transform()`** fonksiyonu ile aşağıdaki parametreler kullanılarak dönüştürülecektir:
   - `category="FOOD_AND_DRINK"`
   - `min_rating=4.0`
   - `min_reviews=1000`

4. Dönüştürülen DataFrame, **`load()`** fonksiyonu kullanılarak hedef **PostgreSQL** veritabanındaki **`top_apps`** tablosuna aktarılacaktır.

5. Veri yükleme işleminin başarılı olduğu, tablonun PostgreSQL'den tekrar okunması ve orijinal DataFrame ile karşılaştırılması yoluyla doğrulanacaktır.

6. Sonuç veri seti görüntülenerek ETL veri hattının başarıyla tamamlandığı kontrol edilecektir.

Bu aşama, ham CSV verilerinin otomatik olarak okunması, işlenmesi, dönüştürülmesi ve PostgreSQL veritabanına yüklenmesini sağlayan uçtan uca bir ETL veri hattının nasıl oluşturulacağını göstermektedir.

In [8]:

# Extract the data
apps_data = extract("apps_data.csv")
reviews_data = extract("review_data.csv")

Here is a little bit of information about the data stored in 'apps_data.csv':
'apps_data.csv' dosyasında bulunan veri setine ait temel bilgiler aşağıda gösterilmektedir.

There are 10841 rows and 13 columns in this DataFrame.
Bu DataFrame toplam 10841 satır ve 13 sütundan oluşmaktadır.

The columns in this DataFrame have the following data types:
Bu DataFrame'deki sütunların veri tipleri aşağıdaki gibidir:
App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

To view the DataFrame extracted from 'apps_data.csv', display the value returned by this function!
'apps_data.csv' dosyasından okunan veri setini görüntülemek için fonksiyonun döndürdüğü değeri görüntüleyebilirsiniz.

Here is a little bit of information about the data stored in 'review_data.csv':
'review_data.csv' dosyasında bulunan veri setine ait temel bilgiler aşağıda gösterilmektedir.

There are 64295 rows and 5 columns in this DataFrame.
Bu DataFrame toplam 64295 satır ve 5 sütundan oluşmaktadır.

The columns in this DataFrame have the following data types:
Bu DataFrame'deki sütunların veri tipleri aşağıdaki gibidir:
App                        object
Translated_Review          object
Sentiment                  object
Sentiment_Polarity        float64
Sentiment_Subjectivity    float64
dtype: object

To view the DataFrame extracted from 'review_data.csv', display the value returned by this function!
'review_data.csv' dosyasından okunan veri setini görüntülemek için fonksiyonun döndürdüğü değeri görüntüleyebilirsiniz.

In [9]:
# Transform the data
top_apps_data = transform(
    apps=apps_data,
    reviews=reviews_data,
    category="FOOD_AND_DRINK",
    min_rating=4.0,
    min_reviews=1000
)

Transforming data to curate a dataset with all FOOD_AND_DRINK apps and their corresponding reviews with a rating of at least 4.0 and 1000 reviews.
Veri dönüştürme işlemi başlatıldı. 'FOOD_AND_DRINK' kategorisindeki, puanı en az 4.0 olan ve en az 1000 incelemeye sahip uygulamalar analiz edilmektedir.

The transformed DataFrame contains 54 rows and 5 columns. It has been saved as 'top_apps.csv' and is ready for further analysis.
Dönüştürülen DataFrame 54 satır ve 5 sütundan oluşmaktadır. Veri seti 'top_apps.csv' dosyası olarak kaydedildi ve analiz için hazır hale getirildi.

In [12]:
top_apps_loaded = load(
    dataframe=top_apps_data,
    host="localhost",
    port=5432,
    database_name="market_research",
    user="postgres",
    password="12345",
    table_name="top_apps"
)

The original DataFrame has been successfully loaded into PostgreSQL.
Orijinal DataFrame başarıyla PostgreSQL veritabanına yüklendi.

The loaded table has been read from PostgreSQL for validation.
Yüklenen tablo doğrulama amacıyla PostgreSQL veritabanından okunmuştur.

Success! The 'top_apps' table has been successfully loaded and validated.
Başarılı! 'top_apps' tablosu PostgreSQL veritabanına başarıyla yüklendi ve doğrulandı.